version: '3.5'

services:
  reverse-proxy: 
    image: jwilder/nginx-proxy
    container_name: reverse-proxy 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
    depends_on:
      - frontend-example-docker
      - backend-example-docker
  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379
  frontend-example-docker:
    image: devopsdockeruh/frontend-example-docker
    container_name: frontend-example-docker
  backend-example-docker:
    image: devopsdockeruh/backend-example-docker
    container_name: backend-example-docker
    environment: 
      - REDIS=redis
      - REDIS_PORT=6379
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - DB_HOST=db
    depends_on: 
      - db