version: '3.5'

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
  frontend-example-docker:
    image: devopsdockeruh/frontend-example-docker
    container_name: frontend-example-docker
    ports: 
      - 5000:5000
  backend-example-docker:
    image: devopsdockeruh/backend-example-docker
    container_name: backend-example-docker
    ports:
      - 8000:8000
    environment: 
      - REDIS=redis
      - REDIS_PORT=6379
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - DB_HOST=db
    depends_on: 
      - db
